//! Legacy VTK structured-points (`.vtk`) reader and writer — `itk::VTKImageIO`.
//!
//! A short text header followed by pixel data that is **always big-endian** when
//! the header says `BINARY`, or whitespace-separated decimal text when it says
//! `ASCII`. `VTKImageIO` reads both and writes whichever `m_FileType` says;
//! SimpleITK never flips that switch, so [`write()`] always emits `BINARY`.
//!
//! # The header ITK writes
//!
//! `WriteImageInformation` (itkVTKImageIO.cxx:638-713) emits exactly:
//!
//! ```text
//! # vtk DataFile Version 3.0
//! VTK File Generated by Insight Segmentation and Registration Toolkit (ITK)
//! BINARY
//! DATASET STRUCTURED_POINTS
//! DIMENSIONS 4 3 2
//! SPACING 5.0000000000000000e-01 1.2500000000000000e+00 3.0000000000000000e+00
//! ORIGIN -2.0000000000000000e+00 4.0000000000000000e+00 7.5000000000000000e+00
//! POINT_DATA 24
//! SCALARS scalars float 1
//! LOOKUP_TABLE default
//! ```
//!
//! Note the trailing space on the `DIMENSIONS` / `SPACING` / `ORIGIN` lines
//! (`<< ' ' << '\n'`), and that the `scientific` / `precision(16)` manipulators
//! are set *after* the `BINARY` line, so only the two float triples carry them.
//! They are `printf("%.16e")`, reproduced by [`scientific16`].
//!
//! A 1-D or 2-D image is padded to three `DIMENSIONS` slots with `1`, three
//! `SPACING` slots with `1.0`, and three `ORIGIN` slots with `0.0` — the
//! `numDims > 1` / `numDims > 2` ternaries at `:674-680`. The **reader collapses
//! the padding back**, so unlike GIPL a 2-D VTK image round-trips as 2-D; see
//! "Dimensions" below. The direction matrix is not written at all and reads back
//! as the identity.
//!
//! `WriteImageInformation` rejects an image whose dimension is not 1, 2 or 3
//! (`:647-651`); `Write` then reopens the file and seeks past the header before
//! writing the pixels.
//!
//! # Dimensions
//!
//! ```cpp
//! if (dims[1] <= 1 && dims[2] <= 1) { this->SetNumberOfDimensions(2); }
//! if (dims[2] <= 1) { this->SetNumberOfDimensions(2); } else { this->SetNumberOfDimensions(3); }
//! ```
//!
//! (`:210-221`) The first `if` is dead — the second subsumes it. The rule that
//! survives is simply *2-D iff `dims[2] <= 1`*, so `DIMENSIONS 4 1 3` is a 3-D
//! image one row tall, and `DIMENSIONS 4 3 1` is 2-D. Ledger §2.100.
//!
//! # The attribute line
//!
//! After `DIMENSIONS`, `InternalReadImageInformation` loops over header lines
//! until one of four attribute keywords appears, matching by **substring** in
//! this order (`:236-352`):
//!
//! 1. `spacing` or `aspect_ratio` — three doubles, first `NDims` kept;
//! 2. `origin` — likewise;
//! 3. `vector` — `numComp = 3`, pixel type `VECTOR`, third token is the
//!    component type;
//! 4. `color_scalars` — `numComp` from the third token (default `1`), pixel type
//!    `1 → SCALAR`, `3 → RGB`, `4 → RGBA`, anything else `VECTOR`; component
//!    type `UCHAR` for `BINARY` and `FLOAT` for `ASCII`, never the file's;
//! 5. `scalars` — third token is the component type, optional fourth is
//!    `numComp` (default `1`); pixel type `SCALAR` at one component and `VECTOR`
//!    otherwise; then one look-ahead line, consumed only if it contains
//!    `lookup_table`;
//! 6. `tensors` — `SYMMETRICSECONDRANKTENSOR`, six components.
//!
//! Any other line — `POINT_DATA 24`, comments — falls through every test and is
//! silently skipped. Because the test is a substring test in that order,
//! `SCALARS vector_field float` is parsed as a `VECTORS` line, and
//! `COLOR_SCALARS` is caught before the `scalars` arm it contains. Ledger §2.101.
//!
//! There is no component-count range check anywhere: upstream's only mention of
//! VTK's documented `(1,4)` range is a `// todo this should be asserted or
//! checked earlier!` comment on the `SCALARS` write branch (`:703-706`). Ledger
//! §2.104.
//!
//! A `TENSORS` file is readable by ITK but not by SimpleITK:
//! `GetPixelIDFromImageIO` has no `SYMMETRICSECONDRANKTENSOR` arm and ends in
//! `"Unknown PixelType"` (sitkImageReaderBase.cxx:213-240). This port
//! **implements** the read (ledger §3.37): a `TENSORS` attribute stores the full
//! 9-component 3×3 matrix per pixel on disk, and `VTKImageIO` reads all nine but
//! keeps the six symmetric components at row-major indices `[0,1,2,4,5,8]` — the
//! diagonal and upper triangle `[a,b,c,d,e,f]` of
//!
//! ```text
//! a b c
//! b d e
//! c e f
//! ```
//!
//! (ASCII `ReadTensorBuffer` hit-hit-hit / skip-hit-hit / skip-skip-hit,
//! `itkVTKImageIO.cxx:415-451`; binary `ReadSymmetricTensorBufferAsBinary`
//! row1=3 / seek1 / row2=2 / seek2 / row3=1, `:494-525`). The result loads as a
//! 6-component vector image.
//!
//! # What a SimpleITK image writes as
//!
//! `sitk::Image` never produces `IOPixelEnum::RGB`/`RGBA` — every
//! multi-component image is an `itk::VectorImage` — so the `COLOR_SCALARS` write
//! branch (`:686-691`) is dead through SimpleITK and [`write()`] never emits it.
//! Reading `COLOR_SCALARS` is fully supported. Ledger §2.102.
//!
//! What is left:
//!
//! * a 3-component vector image → `VECTORS vectors <type>`;
//! * everything else → `SCALARS scalars <type> <ncomp>` + `LOOKUP_TABLE default`,
//!   where `<ncomp>` is the buffer stride (`2` for a complex image).
//!
//! Two consequences, both reproduced. A `ComplexFloat32` image writes as
//! `SCALARS scalars float 2` and reads back as `VectorFloat32` — VTK has no
//! complex type, exactly as MetaImage has none. And a **one**-component vector
//! image writes `SCALARS scalars float 1`, whose reader arm is `numComp == 1 →
//! SCALAR`, so `VectorFloat32` with one component reads back as `Float32`.
//! Ledger §2.103.
//!
//! # 64-bit integers
//!
//! `VTKImageIO::GetComponentTypeAsString` overrides `LONGLONG`/`ULONGLONG` to
//! VTK's `vtktypeint64` / `vtktypeuint64` (`:151-163`) and delegates everything
//! else to `ImageIOBase`. Which of the two an `int64_t` image takes is decided
//! by the host: `MapPixelType<long>` is `LONG` and `MapPixelType<long long>` is
//! `LONGLONG` (itkImageIOBase.h:645-647), and `int64_t` is `long` under LP64
//! (Linux) but `long long` on macOS and Windows. So the same image writes
//! `long` on Linux and `vtktypeint64` on macOS. This port pins the LP64 spelling
//! and accepts all four on read. Ledger §4.72.
//!
//! # ASCII data
//!
//! `Read` delegates to `ImageIOBase::ReadBufferAsASCII`, whose `ReadBuffer`
//! declares `PrintType temp;` **outside** the extraction loop
//! (itkImageIOBase.cxx:800-812). The first `is >> temp` that fails sets `temp`
//! to `0` (or, on overflow, to the saturated limit) and latches `failbit`; every
//! later extraction is a no-op that leaves `temp` alone, so **every remaining
//! component receives that same value**. A short ASCII data block therefore
//! zero-fills rather than erroring. Reproduced by [`read`]; ledger §2.107.
//!
//! `PrintType` is `int` for the three 8-bit component types and the type itself
//! otherwise (itkNumericTraits.h:386/492/614), so `SCALARS scalars
//! unsigned_char 1` ASCII data is decimal integers, not characters, and `300`
//! lands as `44`.
//!
//! Where `PrintType` is unsigned, a negative literal does **not** fail:
//! `num_get::_M_extract_int` accumulates into the unsigned representation and
//! bounds the magnitude by `max`, then negates (locale_facets.tcc:472-475,
//! :576-583). `-1` into an `unsigned short` is `65535` with no `failbit`, while
//! `-70000` overflows to `65535` *with* one. Reproduced by `read_ascii_ints`;
//! ledger §2.105.
//!
//! ASCII **writing** is unreachable through SimpleITK, and lossy where it is
//! reachable: `WriteImageInformation`'s `precision(16)` is set on the `ofstream`
//! it opens and destroys, not on the separate one `Write` opens for the pixel
//! data, which keeps the default 6 significant digits. Not implemented here.
//! Ledger §2.106.
//!
//! # Truncated data and unreadable headers
//!
//! `Read` discards `ReadBufferAsBinary`'s `bool` (`:598`), so a truncated binary
//! file leaves the tail of ITK's freshly-allocated buffer uninitialised and
//! `Read` returns success. C++ UB; [`read`] returns [`IoError::TruncatedData`].
//! Ledger §1.54 / §4.69.
//!
//! `CanReadFile` calls `GetNextLine` four times without catching, so a `.vtk`
//! shorter than four lines makes `ImageIOFactory::CreateImageIO` **throw** where
//! it should have reported "no reader for this file"
//! (`:94-97`). [`VtkImageIo::can_read_file`] returns `false`. Ledger §2.108 /
//! §4.71.
//!
//! `sscanf("%*s %u %u %u", dims, ...)` does not check its return value, and
//! neither do the `SPACING` / `ORIGIN` scans (`:209`, `:241`, `:255`). All three
//! destinations are uninitialised locals (`unsigned int dims[3]`,
//! `double spacing[3]`, `double origin[3]`), so a `DIMENSIONS 4` line leaves
//! `dims[1]` and `dims[2]` indeterminate and sizes the image from them, and an
//! under-filled `SPACING 2.0` line stores indeterminate values through
//! `SetSpacing`; upstream's `1.0` / `0.0` defaults survive only when the line is
//! absent or fully filled. This port raises [`IoError::MalformedVtkHeader`] for
//! an under-filled `DIMENSIONS` and, diverging from upstream, keeps the
//! `1.0` / `0.0` defaults for an under-filled `SPACING` / `ORIGIN` rather than
//! reading indeterminate memory. Ledger §1.55 / §4.70.

use std::collections::BTreeMap;
use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
use std::path::Path;

use crate::core::{Image, PixelBuffer, PixelId};

use crate::io::error::{IoError, Result};
use crate::io::image_io::{ImageInformation, ImageIo};
use crate::io::writer::WriteOptions;

/// The first two header lines `WriteImageInformation` emits, verbatim.
const HEADER_PREAMBLE: &str = "# vtk DataFile Version 3.0\n\
     VTK File Generated by Insight Segmentation and Registration Toolkit (ITK)\n";

fn malformed(what: &str) -> IoError {
    IoError::MalformedVtkHeader(what.to_string())
}

// ---------------------------------------------------------------------------
// Number formatting
// ---------------------------------------------------------------------------

/// `std::ostream` under `setf(scientific, floatfield)` + `precision(16)`, i.e.
/// `printf("%.16e")`: 16 digits after the point and a signed, at-least-two-digit
/// exponent.
///
/// Rust's `{:.16e}` produces the same mantissa but an unpadded, unsigned
/// exponent (`1.0000000000000000e0`), so only the exponent needs rewriting.
pub fn scientific16(v: f64) -> String {
    if v.is_nan() {
        return "nan".to_string();
    }
    if v.is_infinite() {
        return if v < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    let s = format!("{v:.16e}");
    let (mantissa, exp) = s.split_once('e').expect("LowerExp always emits 'e'");
    let exp: i32 = exp.parse().expect("LowerExp emits a decimal exponent");
    let sign = if exp < 0 { '-' } else { '+' };
    format!("{mantissa}e{sign}{:02}", exp.abs())
}

// ---------------------------------------------------------------------------
// Component types
// ---------------------------------------------------------------------------

/// `VTKImageIO::GetComponentTypeAsString` (itkVTKImageIO.cxx:151-163), which
/// falls through to `ImageIOBase::GetComponentTypeAsString`
/// (itkImageIOBase.cxx:399-432) for everything but the two 64-bit `long long`s.
///
/// `Int64` / `UInt64` print as `long` / `unsigned_long` because `int64_t` is
/// `long` on this port's reference platform; see the module docs (§4.72).
fn component_type_as_string(component: PixelId) -> &'static str {
    match component {
        PixelId::UInt8 => "unsigned_char",
        PixelId::Int8 => "char",
        PixelId::UInt16 => "unsigned_short",
        PixelId::Int16 => "short",
        PixelId::UInt32 => "unsigned_int",
        PixelId::Int32 => "int",
        PixelId::UInt64 => "unsigned_long",
        PixelId::Int64 => "long",
        PixelId::Float32 => "float",
        PixelId::Float64 => "double",
        other => unreachable!("{other:?} is not a component type"),
    }
}

/// `ImageIOBase::GetComponentTypeFromString` (itkImageIOBase.cxx:434-480),
/// restricted to the types SimpleITK can load. `long` and `unsigned_long` are
/// 64-bit here, as `sizeof(long) == 8` decides upstream
/// (sitkImageReaderBase.cxx:284-295).
fn component_type_from_string(s: &str) -> Option<PixelId> {
    Some(match s {
        "unsigned_char" => PixelId::UInt8,
        "char" => PixelId::Int8,
        "unsigned_short" => PixelId::UInt16,
        "short" => PixelId::Int16,
        "unsigned_int" => PixelId::UInt32,
        "int" => PixelId::Int32,
        "unsigned_long" | "unsigned_long_long" => PixelId::UInt64,
        "long" | "long_long" => PixelId::Int64,
        "float" => PixelId::Float32,
        "double" => PixelId::Float64,
        _ => return None,
    })
}

/// `VTKImageIO::SetPixelTypeFromString` (itkVTKImageIO.cxx:126-149): the base
/// class's exact-match table first, then VTK's own `vtktypeuint64` /
/// `vtktypeint64` as **substring** tests, then `"Unrecognized pixel type"`.
fn set_pixel_type_from_string(s: &str) -> Result<PixelId> {
    if let Some(component) = component_type_from_string(s) {
        return Ok(component);
    }
    if s.contains("vtktypeuint64") {
        Ok(PixelId::UInt64)
    } else if s.contains("vtktypeint64") {
        Ok(PixelId::Int64)
    } else {
        Err(malformed("Unrecognized pixel type"))
    }
}

// ---------------------------------------------------------------------------
// Header parsing
// ---------------------------------------------------------------------------

/// `itk::IOPixelEnum`, restricted to the values `InternalReadImageInformation`
/// can set.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum VtkPixelType {
    Scalar,
    Vector,
    Rgb,
    Rgba,
    SymmetricSecondRankTensor,
}

/// What `InternalReadImageInformation` leaves on the `ImageIOBase`, plus the
/// `m_HeaderSize` it computes from `tellg()`.
struct Header {
    ascii: bool,
    size: Vec<usize>,
    spacing: Vec<f64>,
    origin: Vec<f64>,
    pixel_type: VtkPixelType,
    components: usize,
    component: PixelId,
    header_size: u64,
}

impl Header {
    fn number_of_pixels(&self) -> usize {
        self.size.iter().product()
    }

    /// `ImageReaderBase::GetPixelIDFromImageIO` (sitkImageReaderBase.cxx:200-240).
    fn pixel_id(&self) -> Result<PixelId> {
        if self.components == 1 && self.pixel_type == VtkPixelType::Scalar {
            return Ok(self.component);
        }
        match self.pixel_type {
            // SimpleITK's `GetPixelIDFromImageIO` has no `SYMMETRICSECONDRANKTENSOR`
            // arm, so a `TENSORS` file that `VTKImageIO` reads fine is unreadable
            // through SimpleITK ("Unknown PixelType"). This port's `Image` can hold
            // the data, so the tensor loads as a 6-component vector image: `read`
            // reads the full 9-component 3×3 matrix from disk and keeps the six
            // symmetric components at indices [0,1,2,4,5,8]. Ledger §3.37.
            VtkPixelType::Vector
            | VtkPixelType::Rgb
            | VtkPixelType::Rgba
            | VtkPixelType::SymmetricSecondRankTensor => Ok(self.component.vector_id()),
            // `Scalar` with a component count other than one is unreachable:
            // both arms that set `Scalar` also set `numComp = 1`.
            VtkPixelType::Scalar => Ok(self.component),
        }
    }
}

/// `VTKImageIO::GetNextLine` (itkVTKImageIO.cxx:40-71), iteratively.
///
/// Lowercases the line, skips empty ones, and fails on the sixth consecutive
/// empty line — upstream's `count > 5` guard fires one line later than its own
/// message claims (§2.98). A line with no terminating newline sets `eofbit` even
/// though `getline` delivered its characters, so the last line of a file that
/// does not end in `\n` is a "Premature EOF" (§2.99).
///
/// `offset` accumulates the bytes consumed, standing in for `tellg()`.
fn get_next_line<R: BufRead>(reader: &mut R, offset: &mut u64) -> Result<String> {
    let mut empties = 0usize;
    loop {
        if empties > 5 {
            return Err(malformed(
                "Error of GetNextLine due to consecutive 5 empty lines in the given .*vtk file",
            ));
        }
        let mut buf = Vec::new();
        let n = reader.read_until(b'\n', &mut buf)?;
        *offset += n as u64;
        if buf.last() != Some(&b'\n') {
            return Err(malformed("Premature EOF in reading a line"));
        }
        buf.pop();
        let line = String::from_utf8_lossy(&buf).to_ascii_lowercase();
        if line.is_empty() {
            empties += 1;
            continue;
        }
        return Ok(line);
    }
}

/// `sscanf`'s `%u` over one whitespace-delimited token: an optional sign, then
/// the longest run of digits. Trailing junk is ignored, as `sscanf`'s would be.
/// `None` when no digit follows the sign.
fn scan_u32(token: &str) -> Option<u32> {
    let b = token.as_bytes();
    let mut i = 0;
    let mut negative = false;
    if let Some(&c @ (b'+' | b'-')) = b.first() {
        negative = c == b'-';
        i = 1;
    }
    let start = i;
    let mut value: u64 = 0;
    while i < b.len() && b[i].is_ascii_digit() {
        value = value
            .saturating_mul(10)
            .saturating_add(u64::from(b[i] - b'0'));
        i += 1;
    }
    if i == start {
        return None;
    }
    let value = value.min(u64::from(u32::MAX)) as u32;
    Some(if negative {
        value.wrapping_neg()
    } else {
        value
    })
}

/// `sscanf`'s `%lf` over one whitespace-delimited token: the longest valid
/// floating-point prefix, trailing junk ignored.
fn scan_f64(token: &str) -> Option<f64> {
    let taken = float_prefix_len(token.as_bytes())?;
    token[..taken].parse::<f64>().ok()
}

/// The three numbers on a `DIMENSIONS` / `SPACING` / `ORIGIN` line, after the
/// keyword `sscanf` skips with `%*s`.
fn scan_triple<T>(line: &str, scan: impl Fn(&str) -> Option<T>) -> Vec<T> {
    let mut out = Vec::with_capacity(3);
    for token in line.split_whitespace().skip(1).take(3) {
        match scan(token) {
            Some(v) => out.push(v),
            // `sscanf` stops at the first conversion failure and leaves the
            // remaining arguments untouched.
            None => break,
        }
    }
    out
}

/// `VTKImageIO::InternalReadImageInformation` (itkVTKImageIO.cxx:165-362).
fn parse_header<R: BufRead>(reader: &mut R) -> Result<Header> {
    let mut offset = 0u64;

    get_next_line(reader, &mut offset)?; // "# vtk DataFile Version 3.0"
    get_next_line(reader, &mut offset)?; // title
    let text = get_next_line(reader, &mut offset)?;
    let ascii = if text.contains("ascii") {
        true
    } else if text.contains("binary") {
        false
    } else {
        return Err(malformed("Unrecognized type"));
    };

    let text = get_next_line(reader, &mut offset)?;
    if !text.contains("structured_points") {
        return Err(malformed("Not structured points, can't read"));
    }

    let text = get_next_line(reader, &mut offset)?;
    if !text.contains("dimensions") {
        return Err(malformed("No dimensions defined"));
    }
    let dims = scan_triple(&text, scan_u32);
    // Upstream reads `dims[1]` / `dims[2]` whether or not `sscanf` filled them;
    // an under-filled line is indeterminate there and an error here (§4.70).
    let &[dx, dy, dz] = dims.as_slice() else {
        return Err(malformed("DIMENSIONS needs three values"));
    };

    // `if (dims[1] <= 1 && dims[2] <= 1) SetNumberOfDimensions(2);` is dead code
    // ahead of `if (dims[2] <= 1) 2 else 3` (§2.100).
    let number_of_dimensions = if dz <= 1 { 2 } else { 3 };
    let size: Vec<usize> = [dx, dy, dz][..number_of_dimensions]
        .iter()
        .map(|&d| d as usize)
        .collect();

    let mut spacing = vec![1.0f64; number_of_dimensions];
    let mut origin = vec![0.0f64; number_of_dimensions];

    let (pixel_type, components, component, header_size) = loop {
        let text = get_next_line(reader, &mut offset)?;

        if text.contains("spacing") || text.contains("aspect_ratio") {
            for (slot, v) in spacing.iter_mut().zip(scan_triple(&text, scan_f64)) {
                *slot = v;
            }
        } else if text.contains("origin") {
            for (slot, v) in origin.iter_mut().zip(scan_triple(&text, scan_f64)) {
                *slot = v;
            }
        } else if text.contains("vector") {
            let name = text.split_whitespace().nth(2).unwrap_or("");
            break (
                VtkPixelType::Vector,
                3,
                set_pixel_type_from_string(name)?,
                offset,
            );
        } else if text.contains("color_scalars") {
            let num_comp = text
                .split_whitespace()
                .nth(2)
                .and_then(scan_u32)
                .unwrap_or(1) as usize;
            let pixel_type = match num_comp {
                1 => VtkPixelType::Scalar,
                3 => VtkPixelType::Rgb,
                4 => VtkPixelType::Rgba,
                _ => VtkPixelType::Vector,
            };
            // The file's own component type is never consulted here.
            let component = if ascii {
                PixelId::Float32
            } else {
                PixelId::UInt8
            };
            break (pixel_type, num_comp, component, offset);
        } else if text.contains("scalars") {
            let mut tokens = text.split_whitespace().skip(2);
            let name = tokens.next().unwrap_or("");
            let num_comp = tokens.next().and_then(scan_u32).unwrap_or(1) as usize;
            let pixel_type = if num_comp == 1 {
                VtkPixelType::Scalar
            } else {
                VtkPixelType::Vector
            };
            let component = set_pixel_type_from_string(name)?;

            // "maybe LOOKUP_TABLE default": one look-ahead line, rewound when it
            // turns out to be pixel data.
            let after_scalars = offset;
            let text = get_next_line(reader, &mut offset)?;
            let header_size = if text.contains("lookup_table") {
                offset
            } else {
                after_scalars
            };
            break (pixel_type, num_comp, component, header_size);
        } else if text.contains("tensors") {
            let name = text.split_whitespace().nth(2).unwrap_or("");
            break (
                VtkPixelType::SymmetricSecondRankTensor,
                6,
                set_pixel_type_from_string(name)?,
                offset,
            );
        }
    };

    Ok(Header {
        ascii,
        size,
        spacing,
        origin,
        pixel_type,
        components,
        component,
        header_size,
    })
}

// ---------------------------------------------------------------------------
// Pixel data
// ---------------------------------------------------------------------------

fn buffer_from_be_bytes(component: PixelId, bytes: &[u8]) -> PixelBuffer {
    macro_rules! unpack {
        ($ty:ty, $variant:ident) => {{
            const S: usize = std::mem::size_of::<$ty>();
            PixelBuffer::$variant(
                bytes
                    .chunks_exact(S)
                    .map(|c| <$ty>::from_be_bytes(c.try_into().expect("chunk size")))
                    .collect(),
            )
        }};
    }
    match component {
        PixelId::UInt8 => PixelBuffer::UInt8(bytes.to_vec()),
        PixelId::Int8 => PixelBuffer::Int8(bytes.iter().map(|&b| b as i8).collect()),
        PixelId::UInt16 => unpack!(u16, UInt16),
        PixelId::Int16 => unpack!(i16, Int16),
        PixelId::UInt32 => unpack!(u32, UInt32),
        PixelId::Int32 => unpack!(i32, Int32),
        PixelId::UInt64 => unpack!(u64, UInt64),
        PixelId::Int64 => unpack!(i64, Int64),
        PixelId::Float32 => unpack!(f32, Float32),
        PixelId::Float64 => unpack!(f64, Float64),
        other => unreachable!("{other:?} is not a component type"),
    }
}

/// The row-major indices of an on-disk 3×3 tensor that `VTKImageIO` keeps —
/// the diagonal and upper triangle `[a,b,c,d,e,f]` of
///
/// ```text
/// a b c
/// b d e
/// c e f
/// ```
///
/// i.e. `ReadTensorBuffer`'s hit-hit-hit / skip-hit-hit / skip-skip-hit pattern
/// (itkVTKImageIO.cxx:425-448) and `ReadSymmetricTensorBufferAsBinary`'s
/// row1=3 / seek1 / row2=2 / seek2 / row3=1 (`:494-525`). §3.37.
const TENSOR_KEEP: [usize; 6] = [0, 1, 2, 4, 5, 8];

/// Compact a buffer of full 9-component 3×3 tensors down to the six kept
/// symmetric components per pixel, preserving on-disk order `[a,b,c,d,e,f]`.
fn keep_symmetric_tensor(buffer: PixelBuffer) -> PixelBuffer {
    macro_rules! keep {
        ($v:expr, $variant:ident) => {{
            let mut out = Vec::with_capacity($v.len() / 9 * 6);
            for chunk in $v.chunks_exact(9) {
                for &k in &TENSOR_KEEP {
                    out.push(chunk[k]);
                }
            }
            PixelBuffer::$variant(out)
        }};
    }
    match buffer {
        PixelBuffer::UInt8(v) => keep!(v, UInt8),
        PixelBuffer::Int8(v) => keep!(v, Int8),
        PixelBuffer::UInt16(v) => keep!(v, UInt16),
        PixelBuffer::Int16(v) => keep!(v, Int16),
        PixelBuffer::UInt32(v) => keep!(v, UInt32),
        PixelBuffer::Int32(v) => keep!(v, Int32),
        PixelBuffer::UInt64(v) => keep!(v, UInt64),
        PixelBuffer::Int64(v) => keep!(v, Int64),
        PixelBuffer::Float32(v) => keep!(v, Float32),
        PixelBuffer::Float64(v) => keep!(v, Float64),
    }
}

fn buffer_to_be_bytes(buffer: &PixelBuffer) -> Vec<u8> {
    macro_rules! pack {
        ($v:expr) => {{
            let mut out = Vec::with_capacity(std::mem::size_of_val(&$v[..]));
            for &x in $v.iter() {
                out.extend_from_slice(&x.to_be_bytes());
            }
            out
        }};
    }
    match buffer {
        PixelBuffer::UInt8(v) => v.clone(),
        PixelBuffer::Int8(v) => v.iter().map(|&x| x as u8).collect(),
        PixelBuffer::UInt16(v) => pack!(v),
        PixelBuffer::Int16(v) => pack!(v),
        PixelBuffer::UInt32(v) => pack!(v),
        PixelBuffer::Int32(v) => pack!(v),
        PixelBuffer::UInt64(v) => pack!(v),
        PixelBuffer::Int64(v) => pack!(v),
        PixelBuffer::Float32(v) => pack!(v),
        PixelBuffer::Float64(v) => pack!(v),
    }
}

/// A `std::istream` positioned over the ASCII pixel block, extracting one
/// `PrintType` field at a time.
struct Extractor<'a> {
    bytes: &'a [u8],
    at: usize,
}

impl<'a> Extractor<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Extractor { bytes, at: 0 }
    }

    fn skip_whitespace(&mut self) {
        while self.at < self.bytes.len() && self.bytes[self.at].is_ascii_whitespace() {
            self.at += 1;
        }
    }

    /// The characters `num_get` would collect for an integer: an optional sign
    /// and the longest run of digits. Advances past exactly those characters, so
    /// a `12abc` token yields `12` and leaves the stream on `a`, where the next
    /// extraction fails.
    ///
    /// Returns the sign and the magnitude separately, because `num_get`'s
    /// overflow bound depends on both (see [`read_ascii_ints`]). The magnitude
    /// saturates at `i128::MAX`, which is above every bound it is compared
    /// against.
    fn integer_field(&mut self) -> Option<(bool, i128)> {
        self.skip_whitespace();
        let b = self.bytes;
        let mut i = self.at;
        let mut negative = false;
        if let Some(&c @ (b'+' | b'-')) = b.get(i) {
            negative = c == b'-';
            i += 1;
        }
        let start = i;
        let mut magnitude: i128 = 0;
        while i < b.len() && b[i].is_ascii_digit() {
            magnitude = magnitude
                .saturating_mul(10)
                .saturating_add(i128::from(b[i] - b'0'));
            i += 1;
        }
        if i == start {
            return None;
        }
        self.at = i;
        Some((negative, magnitude))
    }

    /// The same for a floating field.
    fn float_field(&mut self) -> Option<f64> {
        self.skip_whitespace();
        let rest = &self.bytes[self.at..];
        let taken = float_prefix_len(rest)?;
        // Every byte of the prefix is ASCII by construction.
        let text = std::str::from_utf8(&rest[..taken]).ok()?;
        let value = text.parse::<f64>().ok()?;
        self.at += taken;
        Some(value)
    }
}

/// Length of the longest prefix of `b` that is a C floating-point field.
fn float_prefix_len(b: &[u8]) -> Option<usize> {
    let mut i = 0;
    if matches!(b.first(), Some(b'+' | b'-')) {
        i = 1;
    }
    let start = i;
    while i < b.len() && b[i].is_ascii_digit() {
        i += 1;
    }
    let int_digits = i - start;
    let mut frac_digits = 0;
    if i < b.len() && b[i] == b'.' {
        i += 1;
        while i < b.len() && b[i].is_ascii_digit() {
            i += 1;
            frac_digits += 1;
        }
    }
    if int_digits + frac_digits == 0 {
        return None;
    }
    if i < b.len() && (b[i] | 0x20) == b'e' {
        let mut j = i + 1;
        if matches!(b.get(j), Some(b'+' | b'-')) {
            j += 1;
        }
        let exp_start = j;
        while j < b.len() && b[j].is_ascii_digit() {
            j += 1;
        }
        if j > exp_start {
            i = j;
        }
    }
    Some(i)
}

/// `ImageIOBase::ReadBufferAsASCII` for one integer component type.
///
/// `temp` outlives the loop, so a failed extraction's value — `0` on a bad or
/// missing field, the saturated limit on overflow — is what every subsequent
/// component receives (§2.107).
///
/// `min` and `max` are the `PrintType`'s limits, and `min < 0` is what marks it
/// signed. `num_get::_M_extract_int` accumulates the magnitude into the
/// `PrintType`'s *unsigned* representation and bounds it by
/// `(negative && is_signed) ? -min : max` (locale_facets.tcc:472-475). On
/// overflow it stores `(negative && is_signed) ? min : max` and sets `failbit`;
/// otherwise it stores `negative ? -result : result` (`:576-583`). For an
/// unsigned `PrintType` that negation wraps, so `-1` into an `unsigned short`
/// is `65535` and **succeeds**, while `-70000` overflows to `65535` and fails.
/// `cast` reproduces the narrowing conversion, so it must truncate.
fn read_ascii_ints<T>(
    bytes: &[u8],
    count: usize,
    min: i128,
    max: i128,
    cast: fn(i128) -> T,
) -> Vec<T> {
    let signed = min < 0;
    let mut extractor = Extractor::new(bytes);
    let mut temp: i128 = 0;
    let mut failed = false;
    let mut out = Vec::with_capacity(count);
    for _ in 0..count {
        if !failed {
            match extractor.integer_field() {
                None => {
                    temp = 0;
                    failed = true;
                }
                Some((negative, magnitude)) => {
                    let limit = if negative && signed { -min } else { max };
                    if magnitude > limit {
                        temp = if negative && signed { min } else { max };
                        failed = true;
                    } else if negative {
                        temp = -magnitude;
                    } else {
                        temp = magnitude;
                    }
                }
            }
        }
        out.push(cast(temp));
    }
    out
}

/// The same for a floating component type. A field that overflows the target
/// sets it to `±T::MAX` and latches the failure, as `num_get`'s `ERANGE` arm
/// does.
fn read_ascii_floats<T>(bytes: &[u8], count: usize, max: f64, cast: fn(f64) -> T) -> Vec<T> {
    let mut extractor = Extractor::new(bytes);
    let mut temp = 0.0f64;
    let mut failed = false;
    let mut out = Vec::with_capacity(count);
    for _ in 0..count {
        if !failed {
            match extractor.float_field() {
                None => {
                    temp = 0.0;
                    failed = true;
                }
                Some(v) if v.abs() > max => {
                    temp = if v < 0.0 { -max } else { max };
                    failed = true;
                }
                Some(v) => temp = v,
            }
        }
        out.push(cast(temp));
    }
    out
}

fn buffer_from_ascii(component: PixelId, bytes: &[u8], count: usize) -> PixelBuffer {
    match component {
        // `NumericTraits<char>::PrintType` is `int` for all three 8-bit types.
        PixelId::UInt8 => PixelBuffer::UInt8(read_ascii_ints(
            bytes,
            count,
            i32::MIN as i128,
            i32::MAX as i128,
            |v| v as u8,
        )),
        PixelId::Int8 => PixelBuffer::Int8(read_ascii_ints(
            bytes,
            count,
            i32::MIN as i128,
            i32::MAX as i128,
            |v| v as i8,
        )),
        PixelId::UInt16 => {
            PixelBuffer::UInt16(read_ascii_ints(bytes, count, 0, u16::MAX as i128, |v| {
                v as u16
            }))
        }
        PixelId::Int16 => PixelBuffer::Int16(read_ascii_ints(
            bytes,
            count,
            i16::MIN as i128,
            i16::MAX as i128,
            |v| v as i16,
        )),
        PixelId::UInt32 => {
            PixelBuffer::UInt32(read_ascii_ints(bytes, count, 0, u32::MAX as i128, |v| {
                v as u32
            }))
        }
        PixelId::Int32 => PixelBuffer::Int32(read_ascii_ints(
            bytes,
            count,
            i32::MIN as i128,
            i32::MAX as i128,
            |v| v as i32,
        )),
        PixelId::UInt64 => {
            PixelBuffer::UInt64(read_ascii_ints(bytes, count, 0, u64::MAX as i128, |v| {
                v as u64
            }))
        }
        PixelId::Int64 => PixelBuffer::Int64(read_ascii_ints(
            bytes,
            count,
            i64::MIN as i128,
            i64::MAX as i128,
            |v| v as i64,
        )),
        PixelId::Float32 => {
            PixelBuffer::Float32(read_ascii_floats(bytes, count, f64::from(f32::MAX), |v| {
                v as f32
            }))
        }
        PixelId::Float64 => PixelBuffer::Float64(read_ascii_floats(bytes, count, f64::MAX, |v| v)),
        other => unreachable!("{other:?} is not a component type"),
    }
}

fn identity(n: usize) -> Vec<f64> {
    let mut m = vec![0.0; n * n];
    for i in 0..n {
        m[i * n + i] = 1.0;
    }
    m
}

// ---------------------------------------------------------------------------
// The free-function core
// ---------------------------------------------------------------------------

/// Read a legacy VTK structured-points file, `BINARY` or `ASCII`.
///
/// The direction matrix is the identity: the format has no field for it.
pub fn read(path: &Path) -> Result<Image> {
    let mut file = BufReader::new(std::fs::File::open(path)?);
    let header = parse_header(&mut file)?;
    let pixel_id = header.pixel_id()?;

    // A `TENSORS` attribute stores the full 9-component 3×3 matrix per pixel on
    // disk; `VTKImageIO` reads all nine and keeps the six symmetric components at
    // row-major indices [0,1,2,4,5,8] (`ReadTensorBuffer` /
    // `ReadSymmetricTensorBufferAsBinary`, itkVTKImageIO.cxx:415-451, 494-525).
    // Every other pixel type stores exactly `components` values per pixel. §3.37.
    let tensor = header.pixel_type == VtkPixelType::SymmetricSecondRankTensor;
    let on_disk_components = if tensor { 9 } else { header.components };
    let count = header.number_of_pixels() * on_disk_components;
    let mut file = std::fs::File::open(path)?;
    file.seek(SeekFrom::Start(header.header_size))?;

    let buffer = if header.ascii {
        let mut text = Vec::new();
        file.read_to_end(&mut text)?;
        buffer_from_ascii(header.component, &text, count)
    } else {
        let byte_len = count * header.component.size_in_bytes();
        let mut data = vec![0u8; byte_len];
        // `ReadBufferAsBinary`'s `bool` is discarded upstream, leaving the tail
        // of the buffer uninitialised (§1.54); a short file is an error here.
        file.read_exact(&mut data)
            .map_err(|_| IoError::TruncatedData)?;
        buffer_from_be_bytes(header.component, &data)
    };

    // Collapse each on-disk 3×3 tensor to the six kept symmetric components.
    let buffer = if tensor {
        keep_symmetric_tensor(buffer)
    } else {
        buffer
    };

    let dim = header.size.len();
    if pixel_id.is_vector() {
        Image::from_parts_vector(
            buffer,
            header.components,
            header.size,
            header.spacing,
            header.origin,
            identity(dim),
        )
    } else {
        Image::from_parts(
            buffer,
            header.size,
            header.spacing,
            header.origin,
            identity(dim),
        )
    }
    .map_err(IoError::Core)
}

/// Read the header only. `VTKImageIO` puts nothing in the meta-data dictionary.
pub fn read_information(path: &Path) -> Result<ImageInformation> {
    let mut file = BufReader::new(std::fs::File::open(path)?);
    let header = parse_header(&mut file)?;
    let pixel_id = header.pixel_id()?;
    let dimension = header.size.len();
    Ok(ImageInformation {
        pixel_id,
        dimension,
        number_of_components: header.components,
        size: header.size,
        spacing: header.spacing,
        origin: header.origin,
        direction: identity(dimension),
        metadata: BTreeMap::new(),
    })
}

/// The header `WriteImageInformation` emits for `img`, in `BINARY` mode.
fn build_header(img: &Image) -> Result<String> {
    let dim = img.dimension();
    if !(1..=3).contains(&dim) {
        return Err(IoError::UnsupportedVtkFeature(format!(
            "VTK Writer can only write 1, 2 or 3-dimensional images, not {dim}-dimensional"
        )));
    }

    let at = |v: &[f64], i: usize, default: f64| if i < dim { v[i] } else { default };
    let size = |i: usize| if i < dim { img.size()[i] } else { 1 };

    let components = img.buffer_stride();
    let component = img.buffer().component_id();
    let type_name = component_type_as_string(component);

    let mut header = String::from(HEADER_PREAMBLE);
    header.push_str("BINARY\n");
    header.push_str("DATASET STRUCTURED_POINTS\n");
    header.push_str(&format!(
        "DIMENSIONS {} {} {} \n",
        size(0),
        size(1),
        size(2)
    ));
    header.push_str(&format!(
        "SPACING {} {} {} \n",
        scientific16(at(img.spacing(), 0, 1.0)),
        scientific16(at(img.spacing(), 1, 1.0)),
        scientific16(at(img.spacing(), 2, 1.0))
    ));
    header.push_str(&format!(
        "ORIGIN {} {} {} \n",
        scientific16(at(img.origin(), 0, 0.0)),
        scientific16(at(img.origin(), 1, 0.0)),
        scientific16(at(img.origin(), 2, 0.0))
    ));
    header.push_str(&format!("POINT_DATA {}\n", img.number_of_pixels()));

    // The `COLOR_SCALARS` branch needs `IOPixelEnum::RGB`/`RGBA`, which a
    // `sitk::Image` never carries (§2.102), and the `TENSORS` branch needs a
    // pixel type SimpleITK cannot construct.
    if img.pixel_id().is_vector() && components == 3 {
        header.push_str(&format!("VECTORS vectors {type_name}\n"));
    } else {
        header.push_str(&format!("SCALARS scalars {type_name} {components}\n"));
        header.push_str("LOOKUP_TABLE default\n");
    }
    Ok(header)
}

/// Write a legacy VTK structured-points file.
///
/// Always `BINARY`, always big-endian: `m_FileType` defaults to `Binary`
/// (itkVTKImageIO.cxx:32) and SimpleITK exposes no switch for it, and the data
/// is unconditionally swapped to big-endian on write (`:1034-1051`).
pub fn write(img: &Image, path: &Path) -> Result<()> {
    let header = build_header(img)?;
    let mut bytes = header.into_bytes();
    bytes.extend_from_slice(&buffer_to_be_bytes(img.buffer()));
    std::fs::write(path, bytes)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// The ImageIo implementor
// ---------------------------------------------------------------------------

/// `itk::VTKImageIO`.
#[derive(Clone, Copy, Debug, Default)]
pub struct VtkImageIo;

impl ImageIo for VtkImageIo {
    fn name(&self) -> &'static str {
        "VTKImageIO"
    }

    fn supported_read_extensions(&self) -> &'static [&'static str] {
        &[".vtk"]
    }

    fn supported_write_extensions(&self) -> &'static [&'static str] {
        &[".vtk"]
    }

    /// `CanReadFile` (itkVTKImageIO.cxx:73-105): the `.vtk` extension, then the
    /// fourth line must contain `structured_points`. Note it never looks at the
    /// `ASCII`/`BINARY` line.
    ///
    /// Upstream lets `GetNextLine`'s exceptions escape, so a `.vtk` with fewer
    /// than four lines throws out of `ImageIOFactory::CreateImageIO`; here it is
    /// simply not claimed (§4.71).
    fn can_read_file(&self, path: &Path) -> bool {
        if !crate::io::image_io::has_supported_extension(
            path,
            self.supported_read_extensions(),
            true,
        ) {
            return false;
        }
        let Ok(file) = std::fs::File::open(path) else {
            return false;
        };
        let mut reader = BufReader::new(file);
        let mut offset = 0u64;
        let mut line = String::new();
        for _ in 0..4 {
            match get_next_line(&mut reader, &mut offset) {
                Ok(next) => line = next,
                Err(_) => return false,
            }
        }
        line.contains("structured_points")
    }

    fn read_information(&self, path: &Path) -> Result<ImageInformation> {
        read_information(path)
    }

    fn read(&self, path: &Path) -> Result<Image> {
        read(path)
    }

    /// `options` is ignored: `VTKImageIO` has no compressed write path.
    fn write(&self, image: &Image, path: &Path, _options: &WriteOptions) -> Result<()> {
        write(image, path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `WriteImageInformation` sets `scientific` and `precision(16)` on the
    /// header stream, which is `printf("%.16e")`.
    #[test]
    fn scientific16_matches_c_printf() {
        assert_eq!(scientific16(0.0), "0.0000000000000000e+00");
        assert_eq!(scientific16(-0.0), "-0.0000000000000000e+00");
        assert_eq!(scientific16(1.0), "1.0000000000000000e+00");
        assert_eq!(scientific16(0.5), "5.0000000000000000e-01");
        assert_eq!(scientific16(1.25), "1.2500000000000000e+00");
        assert_eq!(scientific16(3.0), "3.0000000000000000e+00");
        assert_eq!(scientific16(-2.0), "-2.0000000000000000e+00");
        assert_eq!(scientific16(7.5), "7.5000000000000000e+00");
        assert_eq!(scientific16(1e-3), "1.0000000000000000e-03");
        assert_eq!(scientific16(1e21), "1.0000000000000000e+21");
        assert_eq!(scientific16(1.0 / 3.0), "3.3333333333333331e-01");
    }

    /// `%u` takes a sign and the longest digit run, ignores trailing junk, and
    /// converts a negative literal by wrapping — a `DIMENSIONS -1 1 1` line
    /// yields `4294967295`, not an error.
    #[test]
    fn scan_u32_follows_sscanf_percent_u() {
        assert_eq!(scan_u32("12"), Some(12));
        assert_eq!(scan_u32("+12"), Some(12));
        assert_eq!(scan_u32("12abc"), Some(12));
        assert_eq!(scan_u32("-1"), Some(u32::MAX));
        assert_eq!(scan_u32("99999999999999"), Some(u32::MAX));
        assert_eq!(scan_u32("abc"), None);
        assert_eq!(scan_u32("+"), None);
        assert_eq!(scan_u32(""), None);
    }

    /// `%lf` takes the longest floating-point prefix; an `e` with no digits
    /// after it is not part of the field.
    #[test]
    fn scan_f64_follows_sscanf_percent_lf() {
        assert_eq!(scan_f64("1.5"), Some(1.5));
        assert_eq!(scan_f64("-2.25"), Some(-2.25));
        assert_eq!(scan_f64(".5"), Some(0.5));
        assert_eq!(scan_f64("3."), Some(3.0));
        assert_eq!(scan_f64("3e2"), Some(300.0));
        assert_eq!(scan_f64("3e+2"), Some(300.0));
        assert_eq!(scan_f64("3e"), Some(3.0));
        assert_eq!(scan_f64("3e+"), Some(3.0));
        assert_eq!(scan_f64("1.5xyz"), Some(1.5));
        assert_eq!(scan_f64("."), None);
        assert_eq!(scan_f64("-"), None);
        assert_eq!(scan_f64("abc"), None);
    }

    /// `sscanf` stops at the first failed conversion and leaves the remaining
    /// arguments as they were, so a short or broken line yields a short vector
    /// and the caller keeps its defaults for the rest.
    #[test]
    fn scan_triple_stops_at_the_first_failed_conversion() {
        assert_eq!(scan_triple("SPACING 1 2 3", scan_f64), vec![1.0, 2.0, 3.0]);
        assert_eq!(
            scan_triple("SPACING 1 2 3 4", scan_f64),
            vec![1.0, 2.0, 3.0]
        );
        assert_eq!(scan_triple("SPACING 1 x 3", scan_f64), vec![1.0]);
        assert_eq!(scan_triple("SPACING", scan_f64), Vec::<f64>::new());
        assert_eq!(scan_triple("DIMENSIONS 4 3 2", scan_u32), vec![4, 3, 2]);
    }

    /// `GetComponentTypeAsString` under LP64, where `int64_t` is `long`.
    #[test]
    fn component_type_names_are_the_lp64_spellings() {
        assert_eq!(component_type_as_string(PixelId::UInt8), "unsigned_char");
        assert_eq!(component_type_as_string(PixelId::Int8), "char");
        assert_eq!(component_type_as_string(PixelId::UInt16), "unsigned_short");
        assert_eq!(component_type_as_string(PixelId::Int16), "short");
        assert_eq!(component_type_as_string(PixelId::UInt32), "unsigned_int");
        assert_eq!(component_type_as_string(PixelId::Int32), "int");
        assert_eq!(component_type_as_string(PixelId::UInt64), "unsigned_long");
        assert_eq!(component_type_as_string(PixelId::Int64), "long");
        assert_eq!(component_type_as_string(PixelId::Float32), "float");
        assert_eq!(component_type_as_string(PixelId::Float64), "double");
    }

    /// `SetPixelTypeFromString` accepts both the C spellings and the
    /// `vtktypeint64` / `vtktypeuint64` aliases, and its `vtktype` arms are
    /// substring tests.
    #[test]
    fn pixel_type_from_string_accepts_both_spellings_of_the_64_bit_types() {
        assert_eq!(component_type_from_string("long"), Some(PixelId::Int64));
        assert_eq!(
            component_type_from_string("long_long"),
            Some(PixelId::Int64)
        );
        assert_eq!(
            component_type_from_string("unsigned_long"),
            Some(PixelId::UInt64)
        );
        assert_eq!(
            component_type_from_string("unsigned_long_long"),
            Some(PixelId::UInt64)
        );
        assert_eq!(component_type_from_string("banana"), None);

        assert_eq!(
            set_pixel_type_from_string("vtktypeint64").unwrap(),
            PixelId::Int64
        );
        assert_eq!(
            set_pixel_type_from_string("vtktypeuint64").unwrap(),
            PixelId::UInt64
        );
        assert!(set_pixel_type_from_string("banana").is_err());
    }
}
